/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.b3.poc.generate.avro.app.model.avro.meuregistro;
/** Representa  ATIVO ou INATIVO */
@org.apache.avro.specific.AvroGenerated
public enum AtivoOuInativo implements org.apache.avro.generic.GenericEnumSymbol<AtivoOuInativo> {
  ATIVO, INATIVO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AtivoOuInativo\",\"namespace\":\"br.com.b3.poc.generate.avro.app.model.avro.meuregistro\",\"doc\":\"Representa  ATIVO ou INATIVO\",\"symbols\":[\"ATIVO\",\"INATIVO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
