/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.b3.poc.generate.avro.app.model.avro.meuregistro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Endereco extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5980774376401742121L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Endereco\",\"namespace\":\"br.com.b3.poc.generate.avro.app.model.avro.meuregistro\",\"fields\":[{\"name\":\"rua\",\"type\":\"string\"},{\"name\":\"cidade\",\"type\":\"string\"},{\"name\":\"cep\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Endereco> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Endereco> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Endereco> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Endereco> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Endereco> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Endereco to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Endereco from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Endereco instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Endereco fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence rua;
  private java.lang.CharSequence cidade;
  private java.lang.CharSequence cep;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Endereco() {}

  /**
   * All-args constructor.
   * @param rua The new value for rua
   * @param cidade The new value for cidade
   * @param cep The new value for cep
   */
  public Endereco(java.lang.CharSequence rua, java.lang.CharSequence cidade, java.lang.CharSequence cep) {
    this.rua = rua;
    this.cidade = cidade;
    this.cep = cep;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return rua;
    case 1: return cidade;
    case 2: return cep;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: rua = (java.lang.CharSequence)value$; break;
    case 1: cidade = (java.lang.CharSequence)value$; break;
    case 2: cep = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'rua' field.
   * @return The value of the 'rua' field.
   */
  public java.lang.CharSequence getRua() {
    return rua;
  }


  /**
   * Sets the value of the 'rua' field.
   * @param value the value to set.
   */
  public void setRua(java.lang.CharSequence value) {
    this.rua = value;
  }

  /**
   * Gets the value of the 'cidade' field.
   * @return The value of the 'cidade' field.
   */
  public java.lang.CharSequence getCidade() {
    return cidade;
  }


  /**
   * Sets the value of the 'cidade' field.
   * @param value the value to set.
   */
  public void setCidade(java.lang.CharSequence value) {
    this.cidade = value;
  }

  /**
   * Gets the value of the 'cep' field.
   * @return The value of the 'cep' field.
   */
  public java.lang.CharSequence getCep() {
    return cep;
  }


  /**
   * Sets the value of the 'cep' field.
   * @param value the value to set.
   */
  public void setCep(java.lang.CharSequence value) {
    this.cep = value;
  }

  /**
   * Creates a new Endereco RecordBuilder.
   * @return A new Endereco RecordBuilder
   */
  public static br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder newBuilder() {
    return new br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder();
  }

  /**
   * Creates a new Endereco RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Endereco RecordBuilder
   */
  public static br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder newBuilder(br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder other) {
    if (other == null) {
      return new br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder();
    } else {
      return new br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder(other);
    }
  }

  /**
   * Creates a new Endereco RecordBuilder by copying an existing Endereco instance.
   * @param other The existing instance to copy.
   * @return A new Endereco RecordBuilder
   */
  public static br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder newBuilder(br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco other) {
    if (other == null) {
      return new br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder();
    } else {
      return new br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder(other);
    }
  }

  /**
   * RecordBuilder for Endereco instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Endereco>
    implements org.apache.avro.data.RecordBuilder<Endereco> {

    private java.lang.CharSequence rua;
    private java.lang.CharSequence cidade;
    private java.lang.CharSequence cep;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.rua)) {
        this.rua = data().deepCopy(fields()[0].schema(), other.rua);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cidade)) {
        this.cidade = data().deepCopy(fields()[1].schema(), other.cidade);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cep)) {
        this.cep = data().deepCopy(fields()[2].schema(), other.cep);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Endereco instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.rua)) {
        this.rua = data().deepCopy(fields()[0].schema(), other.rua);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cidade)) {
        this.cidade = data().deepCopy(fields()[1].schema(), other.cidade);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cep)) {
        this.cep = data().deepCopy(fields()[2].schema(), other.cep);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'rua' field.
      * @return The value.
      */
    public java.lang.CharSequence getRua() {
      return rua;
    }


    /**
      * Sets the value of the 'rua' field.
      * @param value The value of 'rua'.
      * @return This builder.
      */
    public br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder setRua(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.rua = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'rua' field has been set.
      * @return True if the 'rua' field has been set, false otherwise.
      */
    public boolean hasRua() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'rua' field.
      * @return This builder.
      */
    public br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder clearRua() {
      rua = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cidade' field.
      * @return The value.
      */
    public java.lang.CharSequence getCidade() {
      return cidade;
    }


    /**
      * Sets the value of the 'cidade' field.
      * @param value The value of 'cidade'.
      * @return This builder.
      */
    public br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder setCidade(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.cidade = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cidade' field has been set.
      * @return True if the 'cidade' field has been set, false otherwise.
      */
    public boolean hasCidade() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cidade' field.
      * @return This builder.
      */
    public br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder clearCidade() {
      cidade = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cep' field.
      * @return The value.
      */
    public java.lang.CharSequence getCep() {
      return cep;
    }


    /**
      * Sets the value of the 'cep' field.
      * @param value The value of 'cep'.
      * @return This builder.
      */
    public br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder setCep(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.cep = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cep' field has been set.
      * @return True if the 'cep' field has been set, false otherwise.
      */
    public boolean hasCep() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cep' field.
      * @return This builder.
      */
    public br.com.b3.poc.generate.avro.app.model.avro.meuregistro.Endereco.Builder clearCep() {
      cep = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Endereco build() {
      try {
        Endereco record = new Endereco();
        record.rua = fieldSetFlags()[0] ? this.rua : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cidade = fieldSetFlags()[1] ? this.cidade : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.cep = fieldSetFlags()[2] ? this.cep : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Endereco>
    WRITER$ = (org.apache.avro.io.DatumWriter<Endereco>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Endereco>
    READER$ = (org.apache.avro.io.DatumReader<Endereco>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.rua);

    out.writeString(this.cidade);

    out.writeString(this.cep);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.rua = in.readString(this.rua instanceof Utf8 ? (Utf8)this.rua : null);

      this.cidade = in.readString(this.cidade instanceof Utf8 ? (Utf8)this.cidade : null);

      this.cep = in.readString(this.cep instanceof Utf8 ? (Utf8)this.cep : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.rua = in.readString(this.rua instanceof Utf8 ? (Utf8)this.rua : null);
          break;

        case 1:
          this.cidade = in.readString(this.cidade instanceof Utf8 ? (Utf8)this.cidade : null);
          break;

        case 2:
          this.cep = in.readString(this.cep instanceof Utf8 ? (Utf8)this.cep : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










